# Generated by Django 5.2.4 on 2025-07-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('shoulder_pan_joint', models.FloatField()),
                ('shoulder_lift_joint', models.FloatField()),
                ('elbow_joint', models.FloatField()),
                ('wrist_1_joint', models.FloatField()),
                ('wrist_2_joint', models.FloatField()),
                ('wrist_3_joint', models.FloatField()),
            ],
        ),
    ]
